// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckboxEffectsController from "./checkbox_effects_controller.js"
application.register("checkbox-effects", CheckboxEffectsController)

import FlashController from "./flash_controller.js"
application.register("flash", FlashController)
